# Generated by Django 6.0.2 on 2026-02-22 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('url', models.URLField(unique=True)),
                ('content_raw', models.TextField()),
                ('author', models.TextField(max_length=50)),
                ('hash', models.CharField(max_length=64, unique=True)),
                ('published_at', models.DateTimeField(null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('content_html', models.TextField()),
                ('status', models.CharField(default='draft', max_length=20)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('raw_article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.rawarticle')),
            ],
        ),
    ]
