# Generated by Django 6.0.2 on 2026-03-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_today_in_history_rawarticle_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawarticle',
            name='illustration',
            field=models.ImageField(blank=True, default='core/default.jpg', null=True, upload_to='raw_articles/'),
        ),
    ]
