# Generated by Django 6.0.2 on 2026-03-30 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rawarticle_illustration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawarticle',
            old_name='illustration',
            new_name='image',
        ),
    ]
